language: node_js
node_js:
  - v10
  - v8
  - v6
script: echo "Running tests against $(node -v)..."

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Build
      script: npm run build
    - stage: Produce Coverage
      node_js: node
      script: npm run build && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
